spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource      # 数据源类型
    driver-class-name: org.h2.Driver   # 数据库驱动类
    url: jdbc:h2:mem:common1-dao   # 数据库连接地址，控制台连接时使用
    username: root                     # 用户名，控制台连接时使用
    password: 123456                   # 密码，控制台连接时使用
    schema: classpath:db/createTable-h2.sql
    hikari:
      minimum-idle: 1   # 最小空闲连接数
      maximum-pool-size: 100  # 连接池最大连接数
      connection-timeout: 2000  # 连接超时时间
      idle-timeout: 60000 # 空闲连接超时时间
  h2:
    console:
      enabled: true     # 启用 h2 控制台
      path: /h2-console # h2 web 控制台地址