spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource      # 数据源类型
    driver-class-name: com.mysql.cj.jdbc.Driver   # 数据库驱动类
    url: jdbc:mysql://${mysql.address}:${mysql.port}/${mysql.database}?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&zeroDateTimeBehavior=convertToNull
    # 数据库连接地址
    username: ${mysql.username}                              # 用户名
    password: ${mysql.password}                              # 密码
    hikari:
      minimum-idle: 8   # 最小空闲连接数
      maximum-pool-size: 100  # 连接池最大连接数
      connection-timeout: 2000  # 连接超时时间
      idle-timeout: 60000 # 空闲连接超时时间